version: '3.4'

services:
  mutationtesting.web:
    build:
      target: mutationtests
      cache_from: 
        - mutationtesting.web
    volumes:
      - ${AGENT_BUILDDIRECTORY:-.}/StrykerOutput:/src/MutationTesting.Web.Test.UnitTests/StrykerOutput
      - ${AGENT_BUILDDIRECTORY:-.}/StrykerOutput:/src/MutationTesting.Business.Test.UnitTests/StrykerOutput