version: '3.4'

services:
  mutationtesting.web:
    build:
      target: unittests
      cache_from: 
        - mutationtesting.web
    volumes:
      - ${AGENT_BUILDDIRECTORY:-.}/TestResults:/src/TestResults